name: Start VPS

on: workflow_dispatch

jobs:
  run:
    runs-on: windows-latest
    steps:
      - name: Install & Start Code-Server
        run: |
          curl -fsSL https://code-server.dev/install.sh | sh
          code-server --bind-addr 0.0.0.0:8080 --auth none
